### ISSUE TITLE
Let's encrypt certificate installation issue

### ISSUE THREAD

**Issue by ronnysteiner** [magicdude4eva/PiHoleCloudFlareD#1]
Hi there,

first I'd like to thank you for this great writeup on how to setup Pi-hole with Let's encrypt!

Unfortunately, I've got a problem after running the following command:
acme.sh --force --issue  --dnssleep 30 --dns dns_cf -d pihole.example.com  --reloadcmd "cat /root/.acme.sh/pihole.example.com/pihole.example.com.key /root/.acme.sh/pihole.example.com/pihole.example.com.cer | tee /root/.acme.sh/pihole.example.com/pihole.example.com.combined.pem && systemctl restart lighttpd.service"

I can see that the certs are issued, but after that, I always receive the following error:
sed: -e expression #1, char 171: unknown option to `s'

cat: /root/.acme.sh/pihole.mydomain.tld/pihole.mydomain.tld.key: Permission denied
cat: /root/.acme.sh/pihole.mydomain.tld/pihole.mydomain.tld.cer: Permission denied
tee: /root/.acme.sh/pihole.mydomain.tld/pihole.mydomain.tld.combined.pem: Permission denied

I guess I can run the above command as 'pi' user?
What am I doing wrong?
I'm running the latest Pi-hole 4.0 release.

cheers,
Ronny

**Comment by magicdude4eva** [comment]
Sorry, I was not clear in my instructions. You should run those commands as root user. It will then also install the crontab and the restart command when the cert is renewed.
